-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/FilePermissions/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE fileperm_levels (
  fpl_page INTEGER NOT NULL,
  fpl_level TEXT NOT NULL,
  PRIMARY KEY(fpl_page)
);
