-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/FilePermissions/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/fileperm_levels (
  fpl_page INT UNSIGNED NOT NULL,
  fpl_level VARBINARY(255) NOT NULL,
  PRIMARY KEY(fpl_page)
) /*$wgDBTableOptions*/;
